"""Все клавиатуры бота."""

from . import factories, inline, reply
from .inline import (
    admin_menu_keyboard,
    admin_order_keyboard,
    admin_orders_keyboard,
    admin_promos_keyboard,
    admin_products_keyboard,
    ask_manager_keyboard,
    cart_item_actions,
    cart_keyboard,
    categories_keyboard,
    consultation_keyboard,
    delivery_methods_keyboard,
    faq_keyboard,
    main_inline_menu,
    order_confirm_keyboard,
    order_status_keyboard,
    orders_keyboard,
    payment_methods_keyboard,
    product_keyboard,
    product_qty_keyboard,
    products_keyboard,
    promos_keyboard,
)
from .reply import contact_keyboard, main_menu_keyboard, remove_keyboard

__all__ = [
    "factories",
    "inline",
    "reply",
    "main_menu_keyboard",
    "remove_keyboard",
    "contact_keyboard",
    "main_inline_menu",
    "categories_keyboard",
    "products_keyboard",
    "product_keyboard",
    "product_qty_keyboard",
    "cart_keyboard",
    "cart_item_actions",
    "delivery_methods_keyboard",
    "payment_methods_keyboard",
    "order_confirm_keyboard",
    "orders_keyboard",
    "order_status_keyboard",
    "consultation_keyboard",
    "faq_keyboard",
    "ask_manager_keyboard",
    "promos_keyboard",
    "admin_menu_keyboard",
    "admin_orders_keyboard",
    "admin_order_keyboard",
    "admin_products_keyboard",
    "admin_promos_keyboard",
]
